name: ml-competition
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.3
  - pandas
  - scipy
  - scikit-learn=1.3.0
  - matplotlib
  - seaborn
  - joblib
  - tqdm
  - tabulate
  - xgboost=2.1.3
  - pip
  - pip:
    - hampel
